services:
  app:
    container_name: ailos-sdk
    build: .
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    extra_hosts:
      - "host.docker.internal:host-gateway"